### ISSUE TITLE
Race condition - when waiting for task_balance_ to go from 1 to 0

### ISSUE THREAD

**Issue by Arunass** [bloomen/cxxpool#1]
Suppose you call one of the wait methods when task_balance_ == 1.
In std::wait, the predicate is checked - returns false
Worker thread finishes task, decrements task_balance_
Worker thread signals condition variable
In std::wait, condition variable::wait starts waiting for the signal - never gets it.

It's one of those extremely unlikely things to happen that invariably one hits in production code.

The solution is that the wait_mutex_ must be locked by the worker thread, at least for decrementing task_balance_ so that it cannot be changed between the check and the unlock-wait operation.  So the decrement happens either before the lock in the wait method, or after that unlock-wait.   If it's before then the predicate will return true.  If it is pushed until after then the notify_all_ will be caught.

```
...
    task.callback()();
    {
      std::lock_guard<std::mutex> lock{wait_mutex_};
      --task_balance_;
   }
    wait_cond_var_.notify_all();
}
```

**Comment by bloomen** [comment]
Yes, good catch!
Similar arguments hold for the push() method as it can be called from a different thread than wait().
Already pushed a fix for it. Will be part of the next version.
