### ISSUE TITLE
How to shut down if pool is static?

### ISSUE THREAD

**Issue by garyo** [bloomen/cxxpool#2]
I have at top level (static):
```
static cxxpool::thread_pool threadpool;
```
In my init code I do:
```
  int nthreads = std::thread::hardware_concurrency();
  threadpool.add_threads(nthreads);
```
In my shutdown code, how can I shut down all the threads? I don't think I should call the destructor explicitly, however `threadpool.shutdown()` is private.
In my code, it's possible that after I shut things down they may get restarted, at which point I'd re-add some more threads, so I want the threadpool object to stay around.

**Comment by bloomen** [comment]
How about you simply used a pointer?
```
static std::unique_ptr<cxxpool::thread_pool> pool;
```
Then to create:
```
pool = std::make_unique<cxxpool::thread_pool>(4);
```
and to destroy:
```
pool.reset();
```
Would this work for your use case?

**Comment by garyo** [comment]
Yes, I'll do that if that's the best option. Would be nice to allow deleting threads in the future perhaps.

**Comment by bloomen** [comment]
Adding a new method to delete all threads should be ok. Deleting individual threads is pretty tricky, however, since some or all threads may be busy.
