### ISSUE TITLE
cxxpool uses deprecated `std::result_of`

### ISSUE THREAD

**Issue by garyo** [bloomen/cxxpool#4]
I notice when compiling cxxpool code with c++17 on Mac, I get many of these deprecation warnings:

```
cxxpool/src/cxxpool.h:26:27: warning: 'result_of<void (std::future<void>::*(std::future<void>))()>' is deprecated [-Wdeprecated-declarations]
    typedef typename std::result_of<decltype(&future_type::get)(future_type)>::type value_type;
                          ^
cxxpool/src/cxxpool.h:91:62: note: in instantiation of template class 'cxxpool::detail::future_info<std::__wrap_iter<std::future<void> *>>' requested here
         typename = typename std::enable_if<cxxpool::detail::future_info<Iterator>::is_void>::type>
                                                             ^
cxxpool/src/cxxpool.h:93:6: note: in instantiation of default argument for 'get<std::__wrap_iter<std::future<void> *>>' required here
void get(Iterator first, Iterator last) {
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Here is the rationale for the deprecation: https://en.cppreference.com/w/cpp/types/result_of#Notes
Could cxxpool replace `std::result_of` with `std::invoke_result` to avoid these warnings?

**Comment by bloomen** [comment]
Thanks for the feedback! `std::invoke_result` was only added in C++17 but cxxpool is supposed to be compatible back to C++11. I made this change instead using `std::declval`: https://github.com/bloomen/cxxpool/commit/4d8526e93771c4728cbdcd238369e434bad58d32
Does this work for you?

**Comment by garyo** [comment]
Thanks -- that seems nice & simple.

**Comment by garyo** [comment]
Tested this; works fine for me. Thanks!
